models_tables = [
'MODEL_USER_CLASSIFICATION',
"MODEL_ASSESSMENT_YEARS",
"MODEL_CAPEX",
"MODEL_CALCULATED_ASSESSMENT",
"MODEL_DEBT",
"MODEL_FIXED_ASSETS",
"MODEL_MODAL_WINDOWS",
"MODEL_PYG_ITEM",
"MODEL_CAPEX_VALUES",
"MODEL_PROJECTED_DEBT",
"MODEL_FCLO_DISCOUNT",
"MODEL_PROJECTED_FIXED_ASSETS",
"MODEL_MODAL_WINDOWS_PROJECTED",
"MODEL_PROJECTED_PYG",
]


assessment_tables = [
'USER_CLASSIFICATION',
"ASSESSMENT_YEARS",
"CAPEX",
"CALCULATED_ASSESSMENT",
"DEBT",
"FIXED_ASSETS",
"MODAL_WINDOWS",
"PYG_ITEM",
"CAPEX_VALUES",
"PROJECTED_DEBT",
"FCLO_DISCOUNT",
"PROJECTED_FIXED_ASSETS",
"MODAL_WINDOWS_PROJECTED",
"PROJECTED_PYG",
]


simple_atributes_tables = {'CAPEX': ['CAPEX_NAME', 'USED_ACCOUNT_NAME', 'METHOD', 'TIME_PERIOD', 'PERIODS', 'CALCULATION_COMMENT'],
                                'DEBT': ['ORIGINAL_VALUE', 'ACCOUNT_NUMBER', 'ALIAS_NAME', 'PROJECTION_TYPE', 'START_YEAR', 'ENDING_YEAR', 'DEBT_COMMENT', 'RATE_COMMENT', 'SPREAD_COMMENT'],
                                'FIXED_ASSETS': ['ID_ITEMS_GROUP', 'PROJECTION_TYPE', 'ASSET_ACCOUNT', 'ACUMULATED_ACCOUNT', 'PERIOD_ACCOUNT', 'PROJECTED_YEARS', 'CALCULATION_COMMENT'],
                                'MODAL_WINDOWS': ['ACCOUNT_NUMBER', 'CONTEXT_WINDOW', 'VS_ACCOUNT_NAME', 'PROJECTION_TYPE', 'COMMENT'],
                                'PYG_ITEM': ['ID_RAW_PYG', 'ID_DEPENDENCE', 'PROJECTION_TYPE', 'COMMENT'],
                                'USER_CLASSIFICATION': ['ACCOUNT_NUMBER', 'ID_RAW_CLASSIFICATION'],
                                'CALCULATED_ASSESSMENT': ['ASSESSMENT_DATE', 'INITIAL_DATE', 'DATES_ADJUST_ATRIBUTE', 'DATES_ADJUST_COMMENT', 'CHOSEN_FLOW_NAME', 'GRADIENT', 'TERMINAL_VALUE', 'TOTAL_NOT_OPERATIONAL_ASSETS', 'TOTAL_OPERATIONAL_PASIVES', 'OUTSTANDING_SHARES', 'ADJUST_METHOD', ]
}


ordered_atributes_tables = {'CAPEX_VALUES': {'columns': ['CAPEX_NAME', 'CALCULATED_DATE', 'MANUAL_PERCENTAGE', 'CAPEX_SUMMARY', 'CAPEX_ACUMULATED'], 'order':'CALCULATED_DATE'},
                                'PROJECTED_DEBT': {'columns': ['ITEM_DATE', 'ACCOUNT_NUMBER', 'ALIAS_NAME', 'INITIAL_BALANCE', 'DISBURSEMENT', 'AMORTIZATION', 'ENDING_BALANCE', 'INTEREST_VALUE','ENDING_BALANCE_VARIATION', 'RATE_ATRIBUTE', 'SPREAD_ATRIBUTE'], 'order':'ITEM_DATE'},
                                'FCLO_DISCOUNT': {'columns': ['ITEM_DATE', 'DISCOUNT_PERIOD', 'DISCOUNT_RATE', 'DISCOUNT_FACTOR'], 'order':'ITEM_DATE'},
                                'PROJECTED_FIXED_ASSETS': {'columns': ['PROJECTED_DATE', 'ID_ITEMS_GROUP', 'ASSET_VALUE', 'ACUMULATED_VALUE', 'EXISTING_ASSET_VALUE', 'PERIOD_VALUE'], 'order':'PROJECTED_DATE'},
                                'MODAL_WINDOWS_PROJECTED': {'columns': ['PROJECTED_DATE', 'ACCOUNT_NUMBER', 'CONTEXT_WINDOW', 'ATRIBUTE', 'VALUE'], 'order': 'PROJECTED_DATE'},
                                'PROJECTED_PYG': {'columns': ['PROJECTED_DATE', 'ID_RAW_PYG', 'ATRIBUTE', 'VALUE'], 'order':'PROJECTED_DATE'}}