queries = {'Classification_A': 'SELECT * FROM ORIGINAL_PUC A, ARCHIVE B, ASSESSMENT C WHERE A.ID_ARCHIVE = B.ID AND B.ID = C.ID_ARCHIVE AND C.ID = {}',
    'Classification_B': 'SELECT * FROM USER_CLASSIFICATION WHERE ID_ASSESSMENT = {}',
    'raw_classification': 'SELECT * FROM RAW_CLASSIFICATION',
    'raw_pyg': 'SELECT * FROM RAW_PYG',
    'pyg_base': 'SELECT * FROM PYG_RESULTS WHERE ID_ASSESSMENT = {}',
    'pyg_projections': 'SELECT B.*, A.PROJECTION_TYPE, A.COMMENT, A.ID_DEPENDENCE FROM PYG_ITEM A, PROJECTED_PYG B WHERE A.ID_ASSESSMENT = B.ID_ASSESSMENT AND A.ID_RAW_PYG = B.ID_RAW_PYG AND A.ID_ASSESSMENT = {}',
    'fixed_assets': """SELECT B.PROJECTED_DATE, A.ID_ITEMS_GROUP, A.PROJECTION_TYPE, A.ASSET_ACCOUNT, A.ACUMULATED_ACCOUNT, A.PERIOD_ACCOUNT, A.ASSET_ORIGINAL_VALUE, A.ACUMULATED_ORIGINAL_VALUE, A.PERIOD_ORIGINAL_VALUE, A.PROJECTED_YEARS, 
B.ASSET_VALUE, B.ACUMULATED_VALUE, B.EXISTING_ASSET_VALUE, B.PERIOD_VALUE FROM FIXED_ASSETS A, PROJECTED_FIXED_ASSETS B WHERE A.ID_ASSESSMENT = B.ID_ASSESSMENT AND A.ID_ITEMS_GROUP = B.ID_ITEMS_GROUP AND A.ID_ASSESSMENT = {}""",
    'capex': 'SELECT METHOD, USED_ACCOUNT_NAME, PERIODS FROM CAPEX WHERE ID_ASSESSMENT = {}',
    'capex_dep': 'SELECT * FROM CAPEX_VALUES WHERE ID_ASSESSMENT = {}',
    'cash_flow': 'SELECT A.SUMMARY_DATE, A.VALUE, B.CASH_FLOW_ITEM_NAME FROM CASH_FLOW A, RAW_CASH_FLOW B WHERE A.ID_RAW_CASH_FLOW = B.ID AND A.ID_ASSESSMENT = {}',
    'debt': """SELECT B.`YEAR`, A.*, B.INITIAL_BALANCE, B.AMORTIZATION, B.INTEREST_VALUE, B.ENDING_BALANCE_VARIATION, B.RATE_ATRIBUTE, B.SPREAD_ATRIBUTE FROM DEBT A, PROJECTED_DEBT B 
WHERE A.ID_ASSESSMENT = B.ID_ASSESSMENT AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.ALIAS_NAME = B.ALIAS_NAME AND A.ID_ASSESSMENT = {} ORDER BY A.ACCOUNT_NUMBER DESC, A.ALIAS_NAME, B.YEAR""",
    'modal_window':"""SELECT A.ACCOUNT_NUMBER, A.ORIGINAL_VALUE, A.VS_ACCOUNT_NAME, A.PROJECTION_TYPE, A.COMMENT, A.CONTEXT_WINDOW, B.PROJECTED_DATE, B.ATRIBUTE, B.VALUE 
FROM MODAL_WINDOWS A, MODAL_WINDOWS_PROJECTED B WHERE A.ID_ASSESSMENT = B.ID_ASSESSMENT AND A.CONTEXT_WINDOW = B.CONTEXT_WINDOW AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.ID_ASSESSMENT = {}"""
}

pyg_order = [
'Ingresos operacionales 1',
'Ingresos operacionales 2',
'Ingresos operacionales 3',
'Ingresos operacionales 4',
'Ingresos operacionales 5',
'Ingresos operacionales 6',
'Ingresos operacionales 7',
'Ingresos operacionales 8',
'Ingresos operacionales 9',
'Ingresos operacionales 10',
'Ingresos operacionales 11',
'Ingresos operacionales 12',
'Ingresos operacionales 13',
'Ingresos operacionales 14',
'Ingresos operacionales 15',
'Ingresos operacionales 16',
'Ingresos operacionales 17',
'Ingresos operacionales 18',
'Ingresos operacionales 19',
'Ingresos operacionales 20',
'Ingresos operacionales',
'Costos (Sin depreciación)',
'Utilidad bruta',
'Gastos operacionales 1',
'Gastos operacionales 2',
'Gastos operacionales 3',
'Gastos operacionales 4',
'Gastos operacionales 5',
'Gastos operacionales 6',
'Gastos operacionales 7',
'Gastos operacionales 8',
'Gastos operacionales 9',
'Gastos operacionales 10',
'Gastos operacionales 11',
'Gastos operacionales 12',
'Gastos operacionales 13',
'Gastos operacionales 14',
'Gastos operacionales 15',
'Gastos operacionales 16',
'Gastos operacionales 17',
'Gastos operacionales 18',
'Gastos operacionales 19',
'Gastos operacionales 20',
'Gastos operacionales 21',
'Gastos operacionales 22',
'Gastos operacionales 23',
'Gastos operacionales 24',
'Gastos operacionales 25',
'Gastos operacionales 26',
'Gastos operacionales 27',
'Gastos operacionales 28',
'Gastos operacionales 29',
'Gastos operacionales 30',
'Gastos operacionales',
'Otros ingresos y egresos operativos',
'EBITDA',
'Depreciación del periodo',
'Depreciación Capex',
'Amortización del periodo',
'Deterioro',
'EBIT',
'Otros ingresos y egresos no operativos',
'Intereses/gasto financiero',
'Utilidad antes de impuestos',
'Impuestos de renta',
'Utilidad neta']




cash_flow_order = [
'Utilidad neta',
'Impuestos de renta',
'Intereses/gasto financiero',
'EBIT',
'Impuestos operacionales',
'UODI (NOPAT)',
'Depreciación del periodo',
'Deterioro',
'Amortización del periodo',
'Depreciación Capex',
'Otros movimientos que no son salida ni entrada de efectivo operativos',
'Flujo de caja bruto',
'Capital de trabajo',
'CAPEX',
'Otros movimientos netos de activos operativos que afecta el FCLO',
'Otros ingresos y egresos operativos',
'Flujo de caja Libre Operacional',
'Intereses/gasto financiero FC',
'Impuestos no operacionales',
'Variación de deuda',
'Deuda de tesorería del periodo',
'Deuda de tesorería acumulada',
'Otros movimientos netos de activos operativos que afecta el FCLA',
'Otros ingresos y egresos no operativos',
'Flujo de caja del accionista',
'Aportes de capital social u otros',
'Dividentos en efectivo',
'Flujo de caja del periodo',
'Saldo de caja inicial',
'Saldo de caja final',
'Check',
]